spring:
  data:
    mongodb:
      host: auth-mongodb
      #username: user
      #password: ${MONGODB_PASSWORD}
      database: piggymetrics
      #port: 27017
      #WINDOWS
      port: 25000

server:
  servlet:
    context-path: /uaa
  port: 5000
